### ISSUE TITLE
Fix Duplicate of Duplicates

### ISSUE THREAD

**Issue by ezfe** [Mojira/Arisa.bak#5] opened 2015-08-16 22:19 UTC
Any reports that are marked duplicate of other duplicates should be corrected to be duplicates of the original parent. The extra duplicate links will need to be removed, and any pinned data, and affected versions should be adjusted accordingly.

Originally by @CubeTheThird

**Comment by calebsander** [comment] 2015-08-17 03:00
I think resolving an issue as a dupe of a dupe can be useful sometimes. If the issue seems unrelated to the first report but it is identical to another issue, the user can read the reasoning on the intermediate ticket as to why it's a duplicate.

**Comment by ezfe** [comment] 2015-08-17 03:29
@calebsander correct, however in theory every ticket should relate to a *single* behavior, therefor a ticket is either a dupe or not. "Related" would be for, well, related

**Comment by calebsander** [comment] 2015-08-17 20:41
I just think it can make it easier for the user to see how it is a duplicate without the moderators having to explain it again

**Closed** 2015-09-07 15:58 UTC
Labels: enhancement
